MetamodelAlgemeen.md

Een aantal (typ)fouten hesteld die ik tegenkwam bij lezen van hoofdstuk 2.

Typos en tekstueel

---

MetamodelAlgemeen.md

issue #165 over wat er in een package mag, verwerkt in hfstk 2

issue #165 verwerkt in hfstk 2

---

Inleiding.md

Paragraaf 1.6 bijgewerkt voor https://github.com/Geonovum/MIM-Werkomgeving/issues/179

Update Inleiding.md 1.6 issue 179 

---

Werkversie/rdf/model/media/style.css

Kleur van de kop van alle tabellen aangepast zodat de URIs beter leesbaar zijn.

Aanpassing voor leesbaarheid tabellen

---

MetamodelUML.md

Missende binding in overzichtstabel toegevoegd. Hiermee weer in lijn met het diagram.

add relatie gegevensgroep

---

MetamodelAlgemeen.md

Tekst structuur van definitie en toelichting mag "rijke" tekst zijn

issue 245 rijke tekst

---

MetamodelUML.md

Alle specificatie van metagegevens die betrekking hebben op waardelijsten, in één paragraaf samengebracht.

hersorteer specificatie metagegevens

---

AfsprakenRegels.md
Diagrammen.md
Inleiding.md
MetamodelAlgemeen.md
MetamodelLD.md
MetamodelUML.md

Alle figuren in de documentatie voorzien van <figure> tag met bijschriften.

318 documentatie bijschriften figuren

---

MetamodelAlgemeen.md

Metagegevens
* Basis-URI,
* Ontologie-URI,
* Schema basis-URI en
* Schema URI maken toegevoegd.

issue 188 'URI van model en modelelementen voor publicatie op het web'

---

MetamodelAlgemeen.md
MetamodelUML.md
config.js

Verbeteringen in tekst, structuur en opmaak

Redigeren metamodel algemeen

---

MetamodelLD.md

mim:alias verweest ten onrechte neer mim:naam: aangepast

fix verkeerde verwijzing in ld-tabel

---

AfsprakenRegels.md

In de paragraaf Historie op logisch niveau werd foutief over conceptueel niveau gesproken. Dit is gecorrigeerd.

457 voorbeeld constraint toevoegen

---

Werkversie/rdf/model/Ontologie.md
media/mim-shapes.ttl

Resolves #482 
(Wijziging van plaatjes gebeurt straks in 1 keer onder #484)

mim-ld verwijder metagegevens historie bij gegevensgroep (#482)

---

MetamodelLD.md
TransformatieRDF.md
Werkversie/rdf/model/Ontologie.md
media/mim-shapes.ttl
media/mim.ttl
media/referenties.ttl

Resolves #481 
(Wijziging van plaatjes gebeurt straks in 1 keer onder #484)

mim-ld - mixin toegevoegd (#481)

---

MetamodelAlgemeen.md
MetamodelUML.md

Zie issue #450
Moet ook nog in LD lijkt mij.

issue 450 metagegeven bevat modelelement toegevoegd voor packages

---

TransformatieRDF.md

mim-ld - verwijder type shape transformatie indicatie abstract object (#288)

---

MetamodelAlgemeen.md

Het begrip modelelement kan dus binnen een metamodel als een model worden toegepast.

definitie modelelement aangepast

---

MetamodelUML.md

geen invloed op LD maar er missen wel nog metagegevens bij de LD implementatie van codelijst

datatype verwijderd bij codelijst zie #445

---

MetamodelAlgemeen.md
MetamodelUML.md

verwijderd in hst 2 en 3.
hfst 4 en 6 moet nog.
@pmaria  @architolk

is gedefinieerd in verwijderd

---

MetamodelAlgemeen.md
MetamodelUML.md

Naar **Identificatie**
Gedaan voor hfst 2 en 3. Moet nog voor Hfst 4 en 6.
@pmaria @architolk

Modelelementidentificatie

---

Versielog.md

Aanvulling van de versielog op basis van de wijzigingen uit de consultatieronde.

Versielog mim 1.2
